model_name_or_path: princeton-nlp/Llama-3-Base-8B-SFT
trust_remote_code: true
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.01
pref_loss: sigmoid
dataset: highavg-3
template: llama3
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: ../../../../../data1/dataset_cartography/saves/llama3-8b/plot/highavg
logging_steps: 1
save_steps: 56
plot_loss: true
overwrite_output_dir: true
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 5.0e-07
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
val_size: 0.01
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100
