model_name_or_path: princeton-nlp/Llama-3-Base-8B-SFT
trust_remote_code: true
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_loss: simpo
pref_beta: 2.0
simpo_gamma: 1.0
dataset: pd_lowavg
template: llama3
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: ../../../../../data1/dataset_cartography/saves/llama3-8b/simpo/llama3-8b-simpo-pd_lowavg-32
logging_steps: 10
save_steps: 13
plot_loss: true
overwrite_output_dir: true
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 6.0e-07
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
val_size: 0.01
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100
